server:
  port: 8080

spring:
  application:
    name: reggie_takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wyd358-ysjd
  redis:
    port: 6379
    host: localhost
    database: 0
  cache:
    redis:
      time-to-live: 1800000  #设置缓存过期时间，单位ms

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#文件存储目录路径，通过@Value(${ /.. }})注解赋值给字符串变量
reggie:
  path: D:/reggieImage/